### ISSUE TITLE
Make this an official project?

### ISSUE THREAD

**Issue by tmcw** [documentationjs/grunt-documentation#1]
Want to make this the official documentation grunt binding? I'll add you as an admin for the organization and you could transfer this over, and it would have a shoutout on the http://documentation.js.org/ website

**Comment by SunboX** [comment]
Hey, would be ok for me. I created this out of requirement, I can't guarantee to keep it up-to-date all day.  :smirk: But it shouldn't require much maintenance, let' see. If you add me, I will transfer it.

**Comment by SunboX** [comment]
done. :smirk:

**Comment by SunboX** [comment]
I've to check how to move the `npm` project. Will do this next.
