### ISSUE TITLE
Broken with newest version of documentation

### ISSUE THREAD

**Issue by MeanwhileMedia** [documentationjs/grunt-documentation#13]
This grunt task now exits with no error message, and does not produce output file. I believe it is most likely because of the move to promises in https://github.com/documentationjs/documentation.

The grunt task is no longer synchronous, and exits before completion.

**Comment by MeanwhileMedia** [comment]
Actually, I tried down versioning documentation and it didn't fix the problem. Maybe it's something to do with Grunt v1? Anyone else run into an issue after updating?

**Comment by captbaritone** [comment]
Are you sure you're actually getting the older version? What does `npm ls documentation` return?

**Comment by MeanwhileMedia** [comment]
You're right @captbaritone, I down versioned the wrong location. Thanks.

grunt-documentation does still work with documentation 4.0.0-beta.18

**Comment by tmcw** [comment]
Got it, grunt-documentation, for some reason, uses `latest` versions of everything, which is no good. Looking into it.

**Comment by tmcw** [comment]
I've published & released a stopgap fix in 1.2.2! Sorry about the delay, this repo was transferred into the organization so my repo watching settings were wrong.

**Comment by tmcw** [comment]
1.2.3 is out, and it uses current documentation.js. Greenkeeper will nag me to keep grunt-documentation up to date in the future.

**Comment by MeanwhileMedia** [comment]
Awesome. Thanks for 1.2.3 @tmcw - that was fast. I'll give it a try asap.
