### ISSUE TITLE
documentation is not a function

### ISSUE THREAD

**Issue by craigklem** [documentationjs/grunt-documentation#6]
Getting issue below, have documentation installed both globally and locally. Using in windows 7. Any ideas?

Running "documentation:default" (documentation) task
Verifying property documentation.default exists in config...OK
Files: src/scripts/components/TemplateApp.js -> components/TemplateApp.js
Files: src/scripts/index.js -> index.js
Files: src/scripts/reducers/rootReducer.js -> reducers/rootReducer.js
Files: src/scripts/store/TemplateStore.js -> store/TemplateStore.js
Options: format="html", shallow=false, github=false, access=["public","protected","undefined"], order=[], destin
ation="docs"
Warning: documentation is not a function Use --force to continue.

**Comment by craigklem** [comment]
Config in Gruntfile is:

``` javascript
documentation: {
      default: {
        files: [{
          "expand": true,
          "cwd": "src/scripts",
          src: ['**/*.js'],
        }],
        options: {
          destination: "docs"
        }
      },
    },
```

**Comment by ianwremmel** [comment]
running into the same problem. looks like part of the problem is that grunt-documentation hasn't been adjusted to deal with documentation's change to `import`/`export`.

**Comment by ianwremmel** [comment]
sorry, that's not quite accurate. it seems that the change is simply that documetation no longer exports a function. I think I'll have a PR shortly.

**Comment by SunboX** [comment]
Thx! I will look into it as soon as I get the time to. I'm on vecation next week and I don't know if I get the time before.

**Comment by robertlevy** [comment]
update on this?

**Comment by SunboX** [comment]
jep, but was on vacation last week and bussy at work/in the evening this week. 😢
